goto: handle missing module_path better
This handles using "goto" on "import vim".

I guess Jedi finds the internal "vim" module, but it has no source.

Neovim:

        print(inspect.getfile(vim))
      File "/usr/lib/python3.7/inspect.py", line 666, in getfile
        type(object).__name__))
    TypeError: module, class, method, function, traceback, frame, or code object was expected, got LegacyVim

Vim:

        print(inspect.getfile(vim))
      File "/usr/lib/python3.7/inspect.py", line 647, in getfile
        raise TypeError('{!r} is a built-in module'.format(object))
    TypeError: <module 'vim' (built-in)> is a built-in module